# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#zip api keys
# 1. KZy6juym6W5QxvHzcJhb19XqwcqMr3ob3WinrRJxOOomk5VwPdHQmFhSSHFjL3vO
# 2. bYeWVbePSfIdMJ8hWrvbRrYWxmCJeHGqGUmC6ArZQ9dCSlUPNp1FQZCole7AWO0C
# Top 1000 cities by population, pulled from a JSON file I found on the internet

# Y CID = JTJPGDPMMF3INLQ2BMDJJO4HPKQVLC4CFABKZ3NK43MSWXRD
# Y CS  = 210FXLWIFFMUHNW2JMJUFYQ2LQGKJAFUSN3FV1W2KVWAXW15


# production
cities = City.create([  {name: 'New York' ,state: 'NY'},
						{name: 'Los Angeles' ,state: 'CA'},
						{name: 'Chicago' ,state: 'IL'},
						{name: 'Houston' ,state: 'TX'},
						{name: 'Phoenix' ,state: 'AZ'},
						{name: 'Philadelphia' ,state: 'PA'},
						{name: 'San Antonio' ,state: 'TX'},
						{name: 'Dallas' ,state: 'TX'},
						{name: 'San Diego' ,state: 'CA'},
						{name: 'San Jose' ,state: 'CA'},
						{name: 'Detroit' ,state: 'MI'},
						{name: 'San Francisco' ,state: 'CA'},
						{name: 'Jacksonville' ,state: 'FL'},
						{name: 'Austin' ,state: 'TX'},
						{name: 'Columbus' ,state: 'OH'},
						{name: 'Fort Worth' ,state: 'TX'},
						{name: 'Charlotte' ,state: 'NC'},
						{name: 'Memphis' ,state: 'TN'},
						{name: 'Baltimore' ,state: 'MD'},
						{name: 'El Paso' ,state: 'TX'},
						{name: 'Boston' ,state: 'MA'},
						{name: 'Milwaukee' ,state: 'WI'},
						{name: 'Denver' ,state: 'CO'},
						{name: 'Seattle' ,state: 'WA'},
						{name: 'Nashville' ,state: 'TN'},
						{name: 'Washington' ,state: 'DC'},
						{name: 'Las Vegas' ,state: 'NV'},
						{name: 'Portland' ,state: 'OR'},
						{name: 'Louisville' ,state: 'KY'},
						{name: 'Tucson' ,state: 'AZ'},
						{name: 'Atlanta' ,state: 'GA'},
						{name: 'Albuquerque' ,state: 'NM'},
						{name: 'Fresno' ,state: 'CA'},
						{name: 'Sacramento' ,state: 'CA'},
						{name: 'Long Beach' ,state: 'CA'},
						{name: 'Mesa' ,state: 'AZ'},
						{name: 'Kansas City' ,state: 'MO'},
						{name: 'Cleveland' ,state: 'OH'},
						{name: 'Virginia Beach' ,state: 'VA'},
						{name: 'Miami' ,state: 'FL'},
						{name: 'Oakland' ,state: 'CA'},
						{name: 'Raleigh' ,state: 'NC'},
						{name: 'Minneapolis' ,state: 'MN'},
						{name: 'Colorado Springs' ,state: 'CO'},
						{name: 'Honolulu' ,state: 'HI'},
						{name: 'Arlington' ,state: 'TX'},
						{name: 'Wichita' ,state: 'KS'},
						{name: 'St. Louis' ,state: 'MO'},
						{name: 'Tampa' ,state: 'FL'},
						{name: 'Santa Ana' ,state: 'CA'},
						{name: 'Anaheim' ,state: 'CA'},
						{name: 'Cincinnati' ,state: 'OH'},
						{name: 'Bakersfield' ,state: 'CA'},
						{name: 'Aurora' ,state: 'CO'},
						{name: 'New Orleans' ,state: 'LA'},
						{name: 'Pittsburgh' ,state: 'PA'},
						{name: 'Riverside' ,state: 'CA'},
						{name: 'Toledo' ,state: 'OH'},
						{name: 'Stockton' ,state: 'CA'},
						{name: 'Corpus Christi' ,state: 'TX'},
						{name: 'Lexington' ,state: 'KY'},
						{name: 'St. Paul' ,state: 'MN'},
						{name: 'Anchorage' ,state: 'AK'},
						{name: 'Newark' ,state: 'NJ'},
						{name: 'Buffalo' ,state: 'NY'},
						{name: 'Henderson' ,state: 'NV'},
						{name: 'Lincoln' ,state: 'NE'},
						{name: 'Fort Wayne' ,state: 'IN'},
						{name: 'Glendale' ,state: 'AZ'},
						{name: 'Jersey City' ,state: 'NJ'},
						{name: 'Scottsdale' ,state: 'AZ'},
						{name: 'Madison' ,state: 'WI'},
						{name: 'Orlando' ,state: 'FL'},
						{name: 'Chesapeake' ,state: 'VA'},
						{name: 'Chula Vista' ,state: 'CA'},
						{name: 'Garland' ,state: 'TX'},
						{name: 'North Las Vegas' ,state: 'NV'},
						{name: 'Reno' ,state: 'NV'},
						{name: 'Arlington' ,state: 'VA'},
						{name: 'Akron' ,state: 'OH'},
						{name: 'Irvine' ,state: 'CA'},
						{name: 'Rochester' ,state: 'NY'},
						{name: 'Boise City' ,state: 'ID'},
						{name: 'Fremont' ,state: 'CA'},
						{name: 'Spokane' ,state: 'WA'},
						{name: 'Richmond' ,state: 'VA'},
						{name: 'Shreveport' ,state: 'LA'},
						{name: 'San Bernardino' ,state: 'CA'},
						{name: 'Tacoma' ,state: 'WA'},
						{name: 'Glendale' ,state: 'CA'},
						{name: 'Des Moines' ,state: 'IA'},
						{name: 'Augusta' ,state: 'GA'},
						{name: 'Grand Rapids' ,state: 'MI'},
						{name: 'Mobile' ,state: 'AL'},
						{name: 'Little Rock' ,state: 'AR'},
						{name: 'Knoxville' ,state: 'TN'},
						{name: 'Fort Lauderdale' ,state: 'FL'},
						{name: 'Salt Lake City' ,state: 'UT'},
						{name: 'Tempe' ,state: 'AZ'},
						{name: 'Providence' ,state: 'RI'},
						{name: 'Vancouver' ,state: 'WA'},
						{name: 'Dayton' ,state: 'OH'},
						{name: 'Springfield' ,state: 'MA'},
						{name: 'Eugene' ,state: 'OR'},
						{name: 'Hampton' ,state: 'VA'},
						{name: 'Alexandria' ,state: 'VA'},
						{name: 'Pasadena' ,state: 'CA'},
						{name: 'Hayward' ,state: 'CA'},
						{name: 'Torrance' ,state: 'CA'},
						{name: 'Syracuse' ,state: 'NY'},
						{name: 'Hartford' ,state: 'CT'},
						{name: 'Bellevue' ,state: 'WA'},
						{name: 'New Haven' ,state: 'CT'},
						{name: 'Stamford' ,state: 'CT'},
						{name: 'Clearwater' ,state: 'FL'},
						{name: 'Cambridge' ,state: 'MA'},
						{name: 'South Bend' ,state: 'IN'}])

=begin 
# Comment these out bc the neighborhod api couldn't find any neighborhoods
# Need to explore different options (zillow maybe)
{
	{name: 'Indianapolis' ,state: 'IN'},
	{name: 'Oklahoma City' ,state: 'OK'},
	{name: 'Omaha' ,state: 'NE'},
	{name: 'Tulsa' ,state: 'OK'},
	{name: 'Plano' ,state: 'TX'},
	{name: 'Greensboro' ,state: 'NC'},
	{name: 'Chandler' ,state: 'AZ'},
	{name: 'St. Petersburg' ,state: 'FL'},
	{name: 'Norfolk' ,state: 'VA'},
	{name: 'Birmingham' ,state: 'AL'},
	{name: 'Baton Rouge' ,state: 'LA'},
	{name: 'Durham' ,state: 'NC'},
	{name: 'Laredo' ,state: 'TX'},
	{name: 'Lubbock' ,state: 'TX'},
	{name: 'Winston-Salem' ,state: 'NC'},
	{name: 'Gilbert' ,state: 'AZ'},
	{name: 'Hialeah' ,state: 'FL'},
	{name: 'Modesto' ,state: 'CA'},
	{name: 'Montgomery' ,state: 'AL'},
	{name: 'Yonkers' ,state: 'NY'},
	{name: 'Irving' ,state: 'TX'},
	{name: 'Huntington Beach' ,state: 'CA'},
	{name: 'Moreno Valley' ,state: 'CA'},
	{name: 'Amarillo' ,state: 'TX'},
	{name: 'Columbus' ,state: 'GA'},
	{name: 'Oxnard' ,state: 'CA'},
	{name: 'Fontana' ,state: 'CA'},
	{name: 'Newport News' ,state: 'VA'},
	{name: 'Huntsville' ,state: 'AL'},
	{name: 'Brownsville' ,state: 'TX'},
	{name: 'Worcester' ,state: 'MA'},
	{name: 'Fayetteville' ,state: 'NC'},
	{name: 'Jackson' ,state: 'MS'},
	{name: 'Tallahassee' ,state: 'FL'},
	{name: 'Aurora' ,state: 'IL'},
	{name: '1933 E Locust St, Ontario' ,state: 'CA'},
	{name: 'Overland Park' ,state: 'KS'},
	{name: 'Rancho Cucamonga' ,state: 'CA'},
	{name: 'Chattanooga' ,state: 'TN'},
	{name: 'Oceanside' ,state: 'CA'},
	{name: 'Santa Clarita' ,state: 'CA'},
	{name: 'Garden Grove' ,state: 'CA'},
	{name: 'Grand Prairie' ,state: 'TX'},
	{name: 'Peoria' ,state: 'AZ'},
	{name: 'Rockford' ,state: 'IL'},
	{name: 'Cape Coral' ,state: 'FL'},
	{name: 'Springfield' ,state: 'MO'},
	{name: 'Santa Rosa' ,state: 'CA'},
	{name: 'Sioux Falls' ,state: 'SD'},
	{name: 'Port St. Lucie' ,state: 'FL'},
	{name: 'Salem' ,state: 'OR'},
	{name: 'Pomona' ,state: 'CA'},
	{name: 'Corona' ,state: 'CA'},
	{name: 'Pasadena' ,state: 'TX'},
	{name: 'Joliet' ,state: 'IL'},
	{name: 'Pembroke Pines' ,state: 'FL'},
	{name: 'Paterson' ,state: 'NJ'},
	{name: 'Lancaster' ,state: 'CA'},
	{name: 'Salinas' ,state: 'CA'},
	{name: 'Palmdale' ,state: 'CA'},
	{name: 'Naperville' ,state: 'IL'},
	{name: 'Kansas City' ,state: 'KS'},
	{name: 'Hollywood' ,state: 'FL'},
	{name: 'Lakewood' ,state: 'CO'},
	{name: 'Escondido' ,state: 'CA'},
	{name: 'Fort Collins' ,state: 'CO'},
	{name: 'Bridgeport' ,state: 'CT'},
	{name: 'Orange' ,state: 'CA'},
	{name: 'Warren' ,state: 'MI'},
	{name: 'Elk Grove' ,state: 'CA'},
	{name: 'Savannah' ,state: 'GA'},
	{name: 'Mesquite' ,state: 'TX'},
	{name: 'Sunnyvale' ,state: 'CA'},
	{name: 'Fullerton' ,state: 'CA'},
	{name: 'McAllen' ,state: 'TX'},
	{name: 'Cary' ,state: 'NC'},
	{name: 'Cedar Rapids' ,state: 'IA'},
	{name: 'Sterling Heights' ,state: 'MI'},
	{name: 'Columbia' ,state: 'SC'},
	{name: 'Coral Springs' ,state: 'FL'},
	{name: 'Carrollton' ,state: 'TX'},
	{name: 'Elizabeth' ,state: 'NJ'},
	{name: 'Waco' ,state: 'TX'},
	{name: 'West Valley City' ,state: 'UT'},
	{name: 'Topeka' ,state: 'KS'},
	{name: 'Thousand Oaks' ,state: 'CA'},
	{name: 'El Monte' ,state: 'CA'},
	{name: 'McKinney' ,state: 'TX'},
	{name: 'Concord' ,state: 'CA'},
	{name: 'Visalia' ,state: 'CA'},
	{name: 'Simi Valley' ,state: 'CA'},
	{name: 'Olathe' ,state: 'KS'},
	{name: 'Clarksville' ,state: 'TN'},
	{name: 'Denton' ,state: 'TX'},
	{name: 'Provo' ,state: 'UT'},
	{name: 'Springfield' ,state: 'IL'},
	{name: 'Killeen' ,state: 'TX'},
	{name: 'Abilene' ,state: 'TX'},
	{name: 'Evansville' ,state: 'IN'},
	{name: 'Gainesville' ,state: 'FL'},
	{name: 'Vallejo' ,state: 'CA'},
	{name: 'Ann Arbor' ,state: 'MI'},
	{name: 'Peoria' ,state: 'IL'},
	{name: 'Lansing' ,state: 'MI'},
	{name: 'Lafayette' ,state: 'LA'},
	{name: 'Thornton' ,state: 'CO'},
	{name: 'Athens' ,state: 'GA'},
	{name: 'Flint' ,state: 'MI'},
	{name: 'Inglewood' ,state: 'CA'},
	{name: 'Roseville' ,state: 'CA'},
	{name: 'Charleston' ,state: 'SC'},
	{name: 'Beaumont' ,state: 'TX'},
	{name: 'Independence' ,state: 'MO'},
	{name: 'Victorville' ,state: 'CA'},
	{name: 'Santa Clara' ,state: 'CA'},
	{name: 'Costa Mesa' ,state: 'CA'},
	{name: 'Miami Gardens' ,state: 'FL'},
	{name: 'Manchester' ,state: 'NH'},
	{name: 'Miramar' ,state: 'FL'},
	{name: 'Downey' ,state: 'CA'},
	{name: 'Arvada' ,state: 'CO'},
	{name: 'Allentown' ,state: 'PA'},
	{name: 'Westminster' ,state: 'CO'},
	{name: 'Waterbury' ,state: 'CT'},
	{name: 'Norman' ,state: 'OK'},
	{name: 'Midland' ,state: 'TX'},
	{name: 'Elgin' ,state: 'IL'},
	{name: 'West Covina' ,state: 'CA'},
	{name: 'Pueblo' ,state: 'CO'},
	{name: 'West Jordan' ,state: 'UT'},
	{name: 'Round Rock' ,state: 'TX'},
	{name: 'Billings' ,state: 'MT'},
	{name: 'Erie' ,state: 'PA'},
	{name: 'Ventura' ,state: 'CA'}
}



=begin Comment these out bc we can't handle em yet!
,
					  {name: 'Fairfield' ,state: 'CA'},
					  {name: 'Lowell' ,state: 'MA'},
					  {name: 'Norwalk' ,state: 'CA'},
					  {name: 'Burbank' ,state: 'CA'},
					  {name: 'Richmond' ,state: 'CA'},
					  {name: 'Pompano Beach' ,state: 'FL'},
					  {name: 'High Point' ,state: 'NC'},
					  {name: 'Murfreesboro' ,state: 'TN'},
					  {name: 'Lewisville' ,state: 'TX'},
					  {name: 'Richardson' ,state: 'TX'},
					  {name: 'Daly City' ,state: 'CA'},
					  {name: 'Berkeley' ,state: 'CA'},
					  {name: 'Gresham' ,state: 'OR'},
					  {name: 'Wichita Falls' ,state: 'TX'},
					  {name: 'Green Bay' ,state: 'WI'},
					  {name: 'Davenport' ,state: 'IA'},
					  {name: 'Palm Bay' ,state: 'FL'},
					  {name: 'Columbia' ,state: 'MO'},
					  {name: 'Portsmouth' ,state: 'VA'},
					  {name: 'Rochester' ,state: 'MN'},
					  {name: 'Antioch' ,state: 'CA'},
					  {name: 'Wilmington' ,state: 'NC'},
					  {name: 'Centennial' ,state: 'CO'},
					  {name: 'Odessa' ,state: 'TX'},
					  {name: 'West Palm Beach' ,state: 'FL'},
					  {name: 'Rialto' ,state: 'CA'},
					  {name: 'Everett' ,state: 'WA'},
					  {name: 'Murrieta' ,state: 'CA'},
					  {name: 'Tyler' ,state: 'TX'},
					  {name: 'Temecula' ,state: 'CA'},
					  {name: 'Kenosha' ,state: 'WI'},
					  {name: 'Frisco' ,state: 'TX'},
					  {name: 'Sandy' ,state: 'UT'},
					  {name: 'South Gate' ,state: 'CA'},
					  {name: 'Carlsbad' ,state: 'CA'},
					  {name: 'Gary' ,state: 'IN'},
					  {name: 'Mission Viejo' ,state: 'CA'},
					  {name: 'North Charleston' ,state: 'SC'},
					  {name: 'Boulder' ,state: 'CO'},
					  {name: 'Compton' ,state: 'CA'},
					  {name: 'Hillsboro' ,state: 'OR'},
					  {name: 'Albany' ,state: 'NY'},
					  {name: 'Fargo' ,state: 'ND'},
					  {name: 'Lakeland' ,state: 'FL'},
					  {name: 'Orem' ,state: 'UT'},
					  {name: 'Brockton' ,state: 'MA'},
					  {name: 'Roanoke' ,state: 'VA'},
					  {name: 'Broken Arrow' ,state: 'OK'},
					  {name: 'Surprise' ,state: 'AZ'},
					  {name: 'Macon' ,state: 'GA'},
					  {name: 'El Cajon' ,state: 'CA'},
					  {name: 'Carson' ,state: 'CA'},
					  {name: 'Quincy' ,state: 'MA'},
					  {name: 'Clovis' ,state: 'CA'},
					  {name: 'San Mateo' ,state: 'CA'},
					  {name: 'Vacaville' ,state: 'CA'},
					  {name: 'San Angelo' ,state: 'TX'},
					  {name: 'Las Cruces' ,state: 'NM'},
					  {name: 'Beaverton' ,state: 'OR'},
					  {name: 'Greeley' ,state: 'CO'},
					  {name: 'New Bedford' ,state: 'MA'},
					  {name: 'Livonia' ,state: 'MI'},
					  {name: 'Vista' ,state: 'CA'},
					  {name: 'Fall River' ,state: 'MA'},
					  {name: 'Waukegan' ,state: 'IL'},
					  {name: 'Lawrence' ,state: 'KS'},
					  {name: 'Davie',state: 'FL'},
					  {name: 'Tuscaloosa' ,state: 'AL'},
					  {name: 'Redding' ,state: 'CA'},
					  {name: 'Lawton' ,state: 'OK'},
					  {name: 'Yuma' ,state: 'AZ'},
					  {name: 'Sunrise' ,state: 'FL'},
					  {name: 'Westminster' ,state: 'CA'},
					  {name: 'Sparks' ,state: 'NV'},
					  {name: 'Santa Monica' ,state: 'CA'},
					  {name: 'Roswell' ,state: 'GA'},
					  {name: 'Lynn' ,state: 'MA'},
					  {name: 'Nashua' ,state: 'NH'},
					  {name: 'Dearborn' ,state: 'MI'},
					  {name: 'Santa Maria' ,state: 'CA'},
					  {name: 'Spokane Valley' ,state: 'WA'},
					  {name: 'Santa Barbara' ,state: 'CA'},
					  {name: 'Alhambra' ,state: 'CA'},
					  {name: 'Longmont' ,state: 'CO'},
					  {name: 'Hesperia' ,state: 'CA'},
					  {name: 'Boca Raton' ,state: 'FL'},
					  {name: 'Fort Smith' ,state: 'AR'},
					  {name: 'Miami Beach' ,state: 'FL'},
					  {name: 'Warwick' ,state: 'RI'},
					  {name: 'Indio' ,state: 'CA'},
					  {name: 'Citrus Heights' ,state: 'CA'},
					  {name: 'Deltona' ,state: 'FL'},
					  {name: 'Federal Way' ,state: 'WA'},
					  {name: 'Hawthorne' ,state: 'CA'},
					  {name: 'Duluth' ,state: 'MN'},
					  {name: "Lee's Summit" ,state: 'MO'},
					  {name: 'College Station' ,state: 'TX'},
					  {name: 'Yakima' ,state: 'WA'},
					  {name: 'Kent' ,state: 'WA'},
					  {name: 'Chico' ,state: 'CA'},
					  {name: 'Plantation' ,state: 'FL'},
					  {name: 'Norwalk' ,state: 'CT'},
					  {name: 'Chino' ,state: 'CA'},
					  {name: 'Pearland' ,state: 'TX'},
					  {name: 'Trenton' ,state: 'NJ'},
					  {name: 'Ogden' ,state: 'UT'},
					  {name: 'Sioux City' ,state: 'IA'},
					  {name: 'Sandy Springs' ,state: 'GA'},
					  {name: 'Suffolk' ,state: 'VA'},
					  {name: 'Whittier' ,state: 'CA'},
					  {name: 'Racine' ,state: 'WI'},
					  {name: 'Newton' ,state: 'MA'},
					  {name: 'Avondale' ,state: 'AZ'},
					  {name: 'Bloomington' ,state: 'MN'},
					  {name: 'Allen' ,state: 'TX'},
					  {name: 'Sugar Land' ,state: 'TX'},
					  {name: 'Reading' ,state: 'PA'},
					  {name: 'Cicero',state: 'IL'},
					  {name: 'Nampa' ,state: 'ID'},
					  {name: 'Troy' ,state: 'MI'},
					  {name: 'Livermore' ,state: 'CA'},
					  {name: 'Cranston' ,state: 'RI'},
					  {name: 'Newport Beach' ,state: 'CA'},
					  {name: 'Rio Rancho' ,state: 'NM'},
					  {name: 'Greenville' ,state: 'NC'},
					  {name: 'Edmond' ,state: 'OK'},
					  {name: 'Champaign' ,state: 'IL'},
					  {name: 'Camden' ,state: 'NJ'},
					  {name: 'Buena Park' ,state: 'CA'},
					  {name: 'Danbury' ,state: 'CT'},
					  {name: 'Tracy' ,state: 'CA'},
					  {name: 'San Marcos' ,state: 'CA'},
					  {name: 'Westland' ,state: 'MI'},
					  {name: 'Bellingham' ,state: 'WA'},
					  {name: 'Farmington Hills' ,state: 'MI'},
					  {name: 'Lakewood' ,state: 'CA'},
					  {name: 'Canton' ,state: 'OH'},
					  {name: 'Clifton' ,state: 'NJ'},
					  {name: 'Parma' ,state: 'OH'},
					  {name: 'San Leandro' ,state: 'CA'},
					  {name: 'Evanston' ,state: 'IL'},
					  {name: 'Baldwin Park' ,state: 'CA'},
					  {name: 'Melbourne' ,state: 'FL'},
					  {name: 'Longview' ,state: 'TX'},
					  {name: 'Bend' ,state: 'OR'},
					  {name: 'Merced' ,state: 'CA'},
					  {name: "O'Fallon" ,state: 'MO'},
					  {name: 'Hammond' ,state: 'IN'},
					  {name: 'Decatur' ,state: 'IL'},
					  {name: 'Jacksonville' ,state: 'NC'},
					  {name: 'St. Joseph' ,state: 'MO'},
					  {name: 'Albany' ,state: 'GA'},
					  {name: 'Somerville' ,state: 'MA'},
					  {name: 'Lake Forest' ,state: 'CA'},
					  {name: 'Southfield' ,state: 'MI'},
					  {name: 'Missouri City' ,state: 'TX'},
					  {name: 'Deerfield Beach' ,state: 'FL'},
					  {name: 'Napa' ,state: 'CA'},
					  {name: 'Asheville' ,state: 'NC'},
					  {name: 'New Rochelle' ,state: 'NY'},
					  {name: 'Redwood City' ,state: 'CA'},
					  {name: 'Chino Hills' ,state: 'CA'},
					  {name: 'Arlington Heights' ,state: 'IL'},
					  {name: 'Fayetteville' ,state: 'AR'},
					  {name: 'Medford' ,state: 'OR'},
					  {name: 'Bellflower' ,state: 'CA'},
					  {name: 'Bloomington' ,state: 'IL'},
					  {name: 'Youngstown' ,state: 'OH'},
					  {name: 'Largo' ,state: 'FL'},
					  {name: 'St. George' ,state: 'UT'},
					  {name: 'Lynchburg' ,state: 'VA'},
					  {name: 'Wilmington' ,state: 'DE'},
					  {name: 'Gastonia' ,state: 'NC'},
					  {name: 'Bryan' ,state: 'TX'},
					  {name: 'Palm Coast' ,state: 'FL'},
					  {name: 'Bethlehem' ,state: 'PA'},
					  {name: 'Scranton' ,state: 'PA'},
					  {name: 'Kalamazoo' ,state: 'MI'},
					  {name: 'Union City' ,state: 'CA'},
					  {name: 'Upland' ,state: 'CA'},
					  {name: 'Santa Fe' ,state: 'NM'},
					  {name: 'Bloomington' ,state: 'IN'},
					  {name: 'Tustin' ,state: 'CA'},
					  {name: 'Pawtucket' ,state: 'RI'},
					  {name: 'Schaumburg',state: 'IL'},
					  {name: 'Edinburg' ,state: 'TX'},
					  {name: 'Plymouth' ,state: 'MN'},
					  {name: 'Mountain View' ,state: 'CA'},
					  {name: 'Brooklyn Park' ,state: 'MN'},
					  {name: 'League City' ,state: 'TX'},
					  {name: 'Lake Charles' ,state: 'LA'},
					  {name: 'Hoover' ,state: 'AL'},
					  {name: 'Hemet' ,state: 'CA'},
					  {name: 'Bolingbrook',state: 'IL'},
					  {name: 'Alameda' ,state: 'CA'},
					  {name: 'New Britain' ,state: 'CT'},
					  {name: 'Wyoming' ,state: 'MI'},
					  {name: 'Baytown' ,state: 'TX'},
					  {name: 'Appleton' ,state: 'WI'},
					  {name: 'Lorain' ,state: 'OH'},
					  {name: 'Apple Valley',state: 'CA'},
					  {name: 'Gulfport' ,state: 'MS'},
					  {name: 'Lynwood' ,state: 'CA'},
					  {name: 'Lawrence' ,state: 'MA'},
					  {name: 'Redlands' ,state: 'CA'},
					  {name: 'Flower Mound',state: 'TX'},
					  {name: 'Rochester Hills' ,state: 'MI'},
					  {name: 'Fishers',state: 'IN'},
					  {name: 'Mount Vernon' ,state: 'NY'},
					  {name: 'Turlock' ,state: 'CA'},
					  {name: 'Boynton Beach' ,state: 'FL'},
					  {name: 'Missoula' ,state: 'MT'},
					  {name: 'Springdale' ,state: 'AR'},
					  {name: 'Waukesha' ,state: 'WI'},
					  {name: 'Iowa City' ,state: 'IA'},
					  {name: 'Folsom' ,state: 'CA'},
					  {name: 'Marietta' ,state: 'GA'},
					  {name: 'Milpitas' ,state: 'CA'},
					  {name: 'Rock Hill' ,state: 'SC'},
					  {name: 'Mission' ,state: 'TX'},
					  {name: 'Palatine',state: 'IL'},
					  {name: 'Lauderhill' ,state: 'FL'},
					  {name: 'St. Cloud' ,state: 'MN'},
					  {name: 'Kenner' ,state: 'LA'},
					  {name: 'Meridian' ,state: 'ID'},
					  {name: 'Passaic' ,state: 'NJ'},
					  {name: 'Redondo Beach' ,state: 'CA'},
					  {name: 'Pleasanton' ,state: 'CA'},
					  {name: 'Carmel' ,state: 'IN'},
					  {name: 'Waterloo' ,state: 'IA'},
					  {name: 'Skokie',state: 'IL'},
					  {name: 'Dothan' ,state: 'AL'},
					  {name: 'Concord' ,state: 'NC'},
					  {name: 'Pontiac' ,state: 'MI'},
					  {name: 'Yorba Linda' ,state: 'CA'},
					  {name: 'Loveland' ,state: 'CO'},
					  {name: 'Layton' ,state: 'UT'},
					  {name: 'Rapid City' ,state: 'SD'},
					  {name: 'Mount Pleasant' ,state: 'SC'},
					  {name: 'Eau Claire' ,state: 'WI'},
					  {name: 'Fort Myers' ,state: 'FL'},
					  {name: 'East Orange' ,state: 'NJ'},
					  {name: 'Pharr' ,state: 'TX'},
					  {name: 'North Richland Hills' ,state: 'TX'},
					  {name: 'Manteca' ,state: 'CA'},
					  {name: 'Muncie' ,state: 'IN'},
					  {name: 'Harlingen' ,state: 'TX'},
					  {name: 'Laguna Niguel' ,state: 'CA'},
					  {name: 'St. Charles' ,state: 'MO'},
					  {name: 'Daytona Beach' ,state: 'FL'},
					  {name: 'Pittsburg' ,state: 'CA'},
					  {name: 'Delray Beach' ,state: 'FL'},
					  {name: 'Lafayette' ,state: 'IN'},
					  {name: 'Eagan' ,state: 'MN'},
					  {name: 'Jonesboro' ,state: 'AR'},
					  {name: 'Oshkosh' ,state: 'WI'},
					  {name: 'Weston' ,state: 'FL'},
					  {name: 'Walnut Creek' ,state: 'CA'},
					  {name: 'Camarillo' ,state: 'CA'},
					  {name: 'Kennewick' ,state: 'WA'},
					  {name: 'Jackson' ,state: 'TN'},
					  {name: 'Pico Rivera' ,state: 'CA'},
					  {name: 'Davis' ,state: 'CA'},
					  {name: 'Portland' ,state: 'ME'},
					  {name: 'Victoria' ,state: 'TX'},
					  {name: 'Janesville' ,state: 'WI'},
					  {name: 'South San Francisco' ,state: 'CA'},
					  {name: 'Hamilton' ,state: 'OH'},
					  {name: 'Bossier City' ,state: 'LA'},
					  {name: 'Cedar Park' ,state: 'TX'},
					  {name: 'Kissimmee' ,state: 'FL'},
					  {name: 'Springfield' ,state: 'OH'},
					  {name: 'Renton' ,state: 'WA'},
					  {name: 'Rancho Cordova' ,state: 'CA'},
					  {name: 'Union City' ,state: 'NJ'},
					  {name: 'Johnson City' ,state: 'TN'},
					  {name: 'Montebello' ,state: 'CA'},
					  {name: 'Coon Rapids' ,state: 'MN'},
					  {name: 'Maple Grove' ,state: 'MN'},
					  {name: 'San Clemente' ,state: 'CA'},
					  {name: 'Warner Robins' ,state: 'GA'},
					  {name: 'Lodi' ,state: 'CA'},
					  {name: 'Haverhill' ,state: 'MA'},
					  {name: 'Monterey Park' ,state: 'CA'},
					  {name: 'Yuba City' ,state: 'CA'},
					  {name: 'Eden Prairie' ,state: 'MN'},
					  {name: 'Schenectady' ,state: 'NY'},
					  {name: 'Shawnee' ,state: 'KS'},
					  {name: 'Bristol' ,state: 'CT'},
					  {name: 'Huntington Park' ,state: 'CA'},
					  {name: 'Rockville' ,state: 'MD'},
					  {name: 'Taylor' ,state: 'MI'},
					  {name: 'Bismarck' ,state: 'ND'},
					  {name: 'Encinitas' ,state: 'CA'},
					  {name: 'St. Clair Shores' ,state: 'MI'},
					  {name: 'Waltham' ,state: 'MA'},
					  {name: 'Flagstaff' ,state: 'AZ'},
					  {name: 'Revere' ,state: 'MA'},
					  {name: 'Terre Haute' ,state: 'IN'},
					  {name: 'Greenville' ,state: 'SC'},
					  {name: 'Temple' ,state: 'TX'},
					  {name: 'Council Bluffs' ,state: 'IA'},
					  {name: 'Goodyear' ,state: 'AZ'},
					  {name: 'Johns Creek' ,state: 'GA'},
					  {name: 'North Little Rock' ,state: 'AR'},
					  {name: 'West Allis' ,state: 'WI'},
					  {name: 'Palo Alto' ,state: 'CA'},
					  {name: 'Tamarac' ,state: 'FL'},
					  {name: 'Great Falls' ,state: 'MT'},
					  {name: 'Frederick' ,state: 'MD'},
					  {name: 'Tinley Park' ,state: 'IL'},
					  {name: 'Meriden' ,state: 'CT'},
					  {name: 'La Habra' ,state: 'CA'},
					  {name: 'Burnsville' ,state: 'MN'},
					  {name: 'Taylorsville' ,state: 'UT'},
					  {name: 'Vineland' ,state: 'NJ'},
					  {name: 'Gaithersburg' ,state: 'MD'},
					  {name: 'National City' ,state: 'CA'},
					  {name: 'Gardena' ,state: 'CA'},
					  {name: 'Franklin' ,state: 'TN'},
					  {name: 'Utica' ,state: 'NY'},
					  {name: 'Homestead' ,state: 'FL'},
					  {name: 'Conway' ,state: 'AR'},
					  {name: 'Bayonne' ,state: 'NJ'},
					  {name: 'White Plains' ,state: 'NY'},
					  {name: 'Anderson' ,state: 'IN'},
					  {name: 'Dubuque' ,state: 'IA'},
					  {name: 'Diamond Bar' ,state: 'CA'},
					  {name: 'Springfield' ,state: 'OR'},
					  {name: 'Royal Oak' ,state: 'MI'},
					  {name: 'Galveston' ,state: 'TX'},
					  {name: 'Des Plaines' ,state: 'IL'},
					  {name: 'Rocky Mount' ,state: 'NC'},
					  {name: 'Lakewood' ,state: 'WA'},
					  {name: 'Cheyenne' ,state: 'WY'},
					  {name: 'Rogers' ,state: 'AR'},
					  {name: 'Madera' ,state: 'CA'},
					  {name: 'Tulare' ,state: 'CA'},
					  {name: 'Lake Havasu City' ,state: 'AZ'},
					  {name: 'Ames' ,state: 'IA'},
					  {name: 'Midwest City' ,state: 'OK'},
					  {name: 'Arcadia' ,state: 'CA'},
					  {name: 'Woodbury' ,state: 'MN'},
					  {name: 'Santa Cruz' ,state: 'CA'},
					  {name: 'Auburn' ,state: 'AL'},
					  {name: 'Decatur' ,state: 'AL'},
					  {name: 'Port Arthur' ,state: 'TX'},
					  {name: 'North Miami' ,state: 'FL'},
					  {name: 'Rowlett' ,state: 'TX'},
					  {name: 'Taunton' ,state: 'MA'},
					  {name: 'Blue Springs' ,state: 'MO'},
					  {name: 'Perris' ,state: 'CA'},
					  {name: 'Saginaw' ,state: 'MI'},
					  {name: 'San Rafael' ,state: 'CA'},
					  {name: 'Malden' ,state: 'MA'},
					  {name: 'Medford' ,state: 'MA'},
					  {name: 'Fountain Valley' ,state: 'CA'},
					  {name: 'Owensboro' ,state: 'KY'},
					  {name: 'Orland Park',state: 'IL'},
					  {name: 'St. Peters' ,state: 'MO'},
					  {name: 'Conroe' ,state: 'TX'},
					  {name: 'Auburn' ,state: 'WA'},
					  {name: 'West Des Moines' ,state: 'IA'},
					  {name: 'Pasco' ,state: 'WA'},
					  {name: 'Paramount' ,state: 'CA'},
					  {name: 'Bowling Green' ,state: 'KY'},
					  {name: 'Blaine' ,state: 'MN'},
					  {name: 'Elyria' ,state: 'OH'},
					  {name: 'Chicopee' ,state: 'MA'},
					  {name: 'North Port' ,state: 'FL'},
					  {name: 'Pocatello' ,state: 'ID'},
					  {name: 'Carson City',state: 'NV'},
					  {name: 'Broomfield' ,state: 'CO'},
					  {name: 'Ocala' ,state: 'FL'},
					  {name: 'La Mesa' ,state: 'CA'},
					  {name: 'Petaluma' ,state: 'CA'},
					  {name: 'Lancaster' ,state: 'PA'},
					  {name: 'Port Orange' ,state: 'FL'},
					  {name: 'Woodland' ,state: 'CA'},
					  {name: 'Lakeville' ,state: 'MN'},
					  {name: 'Wellington',state: 'FL'},
					  {name: 'Wheaton' ,state: 'IL'},
					  {name: 'Rosemead' ,state: 'CA'},
					  {name: 'Idaho Falls' ,state: 'ID'},
					  {name: 'Milford' ,state: 'CT'},
					  {name: 'Margate' ,state: 'FL'},
					  {name: 'Novi' ,state: 'MI'},
					  {name: 'Casper' ,state: 'WY'},
					  {name: 'Hempstead' ,state: 'NY'},
					  {name: 'Santee' ,state: 'CA'},
					  {name: 'Pensacola' ,state: 'FL'},
					  {name: 'Kettering' ,state: 'OH'},
					  {name: 'Hoffman Estates', state: 'IL'},
					  {name: 'Cupertino' ,state: 'CA'},
					  {name: 'New Braunfels' ,state: 'TX'},
					  {name: 'Bradenton' ,state: 'FL'},
					  {name: 'Mount Prospect' ,state: 'IL'},
					  {name: 'Oak Lawn' ,state: 'IL'},
					  {name: 'Delano' ,state: 'CA'},
					  {name: 'San Marcos' ,state: 'TX'},
					  {name: 'Rocklin' ,state: 'CA'},
					  {name: 'Novato' ,state: 'CA'},
					  {name: 'Elkhart' ,state: 'IN'},
					  {name: 'Moore' ,state: 'OK'},
					  {name: 'Euless' ,state: 'TX'},
					  {name: 'Bowie' ,state: 'MD'},
					  {name: 'Chapel Hill' ,state: 'NC'},
					  {name: 'West Haven' ,state: 'CT'},
					  {name: 'Sarasota' ,state: 'FL'},
					  {name: 'Manhattan' ,state: 'KS'},
					  {name: 'Cathedral City' ,state: 'CA'},
					  {name: 'Normal',state: 'IL'},
					  {name: 'Battle Creek' ,state: 'MI'},
					  {name: 'Shoreline' ,state: 'WA'},
					  {name: 'Hattiesburg' ,state: 'MS'},
					  {name: 'Dearborn Heights' ,state: 'MI'},
					  {name: 'Porterville' ,state: 'CA'},
					  {name: 'Mentor' ,state: 'OH'},
					  {name: 'Middletown' ,state: 'OH'},
					  {name: 'Niagara Falls' ,state: 'NY'},
					  {name: 'Peabody' ,state: 'MA'},
					  {name: 'Cerritos' ,state: 'CA'},
					  {name: 'Grand Forks' ,state: 'ND'},
					  {name: 'Monroe' ,state: 'LA'},
					  {name: 'New Brunswick' ,state: 'NJ'},
					  {name: 'South Jordan' ,state: 'UT'},
					  {name: 'Corvallis' ,state: 'OR'},
					  {name: 'Highland' ,state: 'CA'},
					  {name: 'Cuyahoga Falls' ,state: 'OH'},
					  {name: 'Lake Elsinore' ,state: 'CA'},
					  {name: 'La Crosse' ,state: 'WI'},
					  {name: 'Palm Desert' ,state: 'CA'},
					  {name: 'Burlington' ,state: 'NC'},
					  {name: 'Lakewood' ,state: 'OH'},
					  {name: 'Sanford' ,state: 'FL'},
					  {name: 'Florissant' ,state: 'MO'},
					  {name: 'Colton' ,state: 'CA'},
					  {name: 'Grapevine' ,state: 'TX'},
					  {name: 'Watsonville' ,state: 'CA'},
					  {name: 'Coconut Creek' ,state: 'FL'},
					  {name: 'Pine Bluff' ,state: 'AR'},
					  {name: 'Charleston' ,state: 'WV'},
					  {name: 'Hanford' ,state: 'CA'},
					  {name: 'Minnetonka' ,state: 'MN'},
					  {name: 'Mishawaka' ,state: 'IN'},
					  {name: 'Apple Valley' ,state: 'MN'},
					  {name: 'Gilroy' ,state: 'CA'},
					  {name: 'Berwyn' ,state: 'IL'},
					  {name: 'Alpharetta' ,state: 'GA'},
					  {name: 'Smyrna' ,state: 'GA'},
					  {name: 'La Mirada' ,state: 'CA'},
					  {name: 'Joplin' ,state: 'MO'},
					  {name: 'Yucaipa' ,state: 'CA'},
					  {name: 'Bellevue' ,state: 'NE'},
					  {name: 'Placentia' ,state: 'CA'},
					  {name: 'Grand Junction' ,state: 'CO'},
					  {name: 'Georgetown' ,state: 'TX'},
					  {name: 'Rancho Santa Margarita' ,state: 'CA'},
					  {name: 'Mansfield' ,state: 'OH'},
					  {name: 'Oak Park',state: 'IL'},
					  {name: 'Redmond' ,state: 'WA'},
					  {name: 'Brentwood' ,state: 'CA'},
					  {name: 'Glendora' ,state: 'CA'},
					  {name: 'Downers Grove',state: 'IL'},
					  {name: 'Palm Beach Gardens' ,state: 'FL'},
					  {name: 'Huntington' ,state: 'WV'},
					  {name: 'San Ramon' ,state: 'CA'},
					  {name: 'Bedford' ,state: 'TX'},
					  {name: 'Jupiter',state: 'FL'},
					  {name: 'Poway' ,state: 'CA'},
					  {name: 'Perth Amboy' ,state: 'NJ'},
					  {name: 'Tigard' ,state: 'OR'},
					  {name: 'Logan' ,state: 'UT'},
					  {name: 'Alexandria' ,state: 'LA'},
					  {name: 'Valdosta' ,state: 'GA'},
					  {name: 'East Providence' ,state: 'RI'},
					  {name: 'Wilson' ,state: 'NC'},
					  {name: 'Albany' ,state: 'OR'},
					  {name: 'Middletown' ,state: 'CT'},
					  {name: 'Palm Springs' ,state: 'CA'},
					  {name: 'Sheboygan' ,state: 'WI'},
					  {name: 'Hendersonville' ,state: 'TN'},
					  {name: 'Greenwood' ,state: 'IN'},
					  {name: 'Stillwater' ,state: 'OK'},
					  {name: 'DeSoto' ,state: 'TX'},
					  {name: 'West Sacramento' ,state: 'CA'},
					  {name: 'Bartlett' ,state: 'TN'},
					  {name: 'Troy' ,state: 'NY'},
					  {name: 'Kentwood' ,state: 'MI'},
					  {name: 'Euclid' ,state: 'OH'},
					  {name: 'Enid' ,state: 'OK'},
					  {name: 'Kirkland' ,state: 'WA'},
					  {name: 'Buckeye',state: 'AZ'},
					  {name: 'Newark' ,state: 'OH'},
					  {name: 'Pinellas Park' ,state: 'FL'},
					  {name: 'Harrisburg' ,state: 'PA'},
					  {name: 'Cypress' ,state: 'CA'},
					  {name: 'Covina' ,state: 'CA'},
					  {name: 'Azusa' ,state: 'CA'},
					  {name: 'Lenexa' ,state: 'KS'},
					  {name: 'Lehi' ,state: 'UT'},
					  {name: 'Roseville' ,state: 'MI'},
					  {name: 'Salina' ,state: 'KS'},
					  {name: 'West New York' ,state: 'NJ'},
					  {name: 'Murray' ,state: 'UT'},
					  {name: 'Roswell' ,state: 'NM'},
					  {name: 'Barnstable Town' ,state: 'MA'},
					  {name: 'Glenview',state: 'IL'},
					  {name: 'Richland' ,state: 'WA'},
					  {name: 'Altoona' ,state: 'PA'},
					  {name: 'Mansfield' ,state: 'TX'},
					  {name: 'Portage' ,state: 'MI'},
					  {name: 'Plainfield' ,state: 'NJ'},
					  {name: 'Chesterfield' ,state: 'MO'},
					  {name: 'Elmhurst' ,state: 'IL'},
					  {name: 'East Lansing' ,state: 'MI'},
					  {name: 'Cleveland Heights' ,state: 'OH'},
					  {name: 'Grand Island' ,state: 'NE'},
					  {name: 'Kokomo' ,state: 'IN'},
					  {name: 'Biloxi' ,state: 'MS'},
					  {name: 'Edina' ,state: 'MN'},
					  {name: 'Maricopa' ,state: 'AZ'},
					  {name: 'DeKalb' ,state: 'IL'},
					  {name: 'St. Louis Park' ,state: 'MN'},
					  {name: 'Olympia' ,state: 'WA'},
					  {name: 'Summerville' ,state: 'SC'},
					  {name: 'Wauwatosa' ,state: 'WI'},
					  {name: 'Cedar Hill' ,state: 'TX'},
					  {name: 'Titusville' ,state: 'FL'},
					  {name: 'Binghamton' ,state: 'NY'},
					  {name: 'Bell Gardens' ,state: 'CA'},
					  {name: 'Danville' ,state: 'VA'},
					  {name: 'Texas City' ,state: 'TX'},
					  {name: 'Bountiful' ,state: 'UT'},
					  {name: 'Kingsport' ,state: 'TN'},
					  {name: 'Castle Rock',state: 'CO'},
					  {name: 'Dublin' ,state: 'CA'},
					  {name: 'Southaven' ,state: 'MS'},
					  {name: 'Methuen' ,state: 'MA'},
					  {name: 'Huntersville' ,state: 'NC'},
					  {name: 'Harrisonburg' ,state: 'VA'},
					  {name: 'Freeport',state: 'NY'},
					  {name: 'La Quinta' ,state: 'CA'},
					  {name: 'Warren' ,state: 'OH'},
					  {name: 'Parker' ,state: 'CO'},
					  {name: 'San Luis Obispo' ,state: 'CA'},
					  {name: 'Lincoln' ,state: 'CA'},
					  {name: 'Oro Valley' ,state: 'AZ'},
					  {name: 'East Point' ,state: 'GA'},
					  {name: "Coeur d'Alene" ,state: 'ID'},
					  {name: 'Sierra Vista' ,state: 'AZ'},
					  {name: 'Woonsocket' ,state: 'RI'},
					  {name: 'Lawrence' ,state: 'IN'},
					  {name: 'Covington' ,state: 'KY'},
					  {name: 'Moline' ,state: 'IL'},
					  {name: 'Buffalo Grove',state: 'IL'},
					  {name: 'Lombard',state: 'IL'},
					  {name: 'Attleboro' ,state: 'MA'},
					  {name: 'Hackensack' ,state: 'NJ'},
					  {name: 'Coral Gables' ,state: 'FL'},
					  {name: 'Bonita Springs' ,state: 'FL'},
					  {name: 'Prescott' ,state: 'AZ'},
					  {name: 'Ceres' ,state: 'CA'},
					  {name: 'Pittsfield' ,state: 'MA'},
					  {name: 'Farmington' ,state: 'NM'},
					  {name: 'Strongsville' ,state: 'OH'},
					  {name: 'Kannapolis' ,state: 'NC'},
					  {name: 'Commerce City' ,state: 'CO'},
					  {name: 'Fairfield' ,state: 'OH'},
					  {name: 'Caldwell' ,state: 'ID'},
					  {name: 'Draper' ,state: 'UT'},
					  {name: 'Oakland Park' ,state: 'FL'},
					  {name: 'Ankeny' ,state: 'IA'},
					  {name: 'The Colony' ,state: 'TX'},
					  {name: 'Concord' ,state: 'NH'},
					  {name: 'Bartlett' ,state: 'IL'},
					  {name: 'Sayreville' ,state: 'NJ'},
					  {name: 'Twin Falls' ,state: 'ID'},
					  {name: 'Noblesville' ,state: 'IN'},
					  {name: 'Fond du Lac' ,state: 'WI'},
					  {name: 'Crystal Lake' ,state: 'IL'},
					  {name: 'Blacksburg',state: 'VA'},
					  {name: 'Newark' ,state: 'CA'},
					  {name: 'North Lauderdale' ,state: 'FL'},
					  {name: 'Chelsea' ,state: 'MA'},
					  {name: 'Aliso Viejo' ,state: 'CA'},
					  {name: 'Charlottesville' ,state: 'VA'},
					  {name: 'Hickory' ,state: 'NC'},
					  {name: 'Salem' ,state: 'MA'},
					  {name: 'Danville',state: 'CA'},
					  {name: 'Casa Grande' ,state: 'AZ'},
					  {name: 'Rancho Palos Verdes' ,state: 'CA'},
					  {name: 'Lompoc' ,state: 'CA'},
					  {name: 'Belleville' ,state: 'IL'},
					  {name: 'Leominster' ,state: 'MA'},
					  {name: 'Wilkes-Barre' ,state: 'PA'},
					  {name: 'Midland' ,state: 'MI'},
					  {name: 'Hutchinson' ,state: 'KS'},
					  {name: 'Fort Pierce' ,state: 'FL'},
					  {name: 'Bullhead City' ,state: 'AZ'},
					  {name: 'Littleton' ,state: 'CO'},
					  {name: 'Jefferson City' ,state: 'MO'},
					  {name: 'Lacey' ,state: 'WA'},
					  {name: 'La Puente' ,state: 'CA'},
					  {name: 'Westfield' ,state: 'MA'},
					  {name: 'Hoboken' ,state: 'NJ'},
					  {name: 'Rohnert Park' ,state: 'CA'},
					  {name: 'San Gabriel' ,state: 'CA'},
					  {name: 'San Bruno' ,state: 'CA'},
					  {name: 'Fitchburg' ,state: 'MA'},
					  {name: 'Haltom City' ,state: 'TX'},
					  {name: 'Sammamish' ,state: 'WA'},
					  {name: 'Edmonds' ,state: 'WA'},
					  {name: 'Muskogee' ,state: 'OK'},
					  {name: 'York' ,state: 'PA'},
					  {name: 'El Centro' ,state: 'CA'},
					  {name: 'Carol Stream' ,state: 'IL'},
					  {name: 'Columbus' ,state: 'IN'},
					  {name: 'Shelton' ,state: 'CT'},
					  {name: 'Quincy' ,state: 'IL'},
					  {name: 'Altamonte Springs' ,state: 'FL'},
					  {name: 'Holyoke' ,state: 'MA'},
					  {name: 'Beavercreek' ,state: 'OH'},
					  {name: 'Cleveland' ,state: 'TN'},
					  {name: 'Riverton' ,state: 'UT'},
					  {name: 'Hagerstown' ,state: 'MD'},
					  {name: 'Pflugerville' ,state: 'TX'},
					  {name: 'Urbana' ,state: 'IL'},
					  {name: 'Leesburg',state: 'VA'},
					  {name: 'Spartanburg' ,state: 'SC'},
					  {name: 'Hot Springs' ,state: 'AR'},
					  {name: 'Bozeman' ,state: 'MT'},
					  {name: 'State College',state: 'PA'},
					  {name: 'Atlantic City' ,state: 'NJ'},
					  {name: 'Muskegon' ,state: 'MI'},
					  {name: 'Coachella' ,state: 'CA'},
					  {name: 'Beverly' ,state: 'MA'},
					  {name: 'Collierville',state: 'TN'},
					  {name: 'Linden' ,state: 'NJ'},
					  {name: 'Coppell' ,state: 'TX'},
					  {name: 'Brookfield' ,state: 'WI'},
					  {name: 'Keller' ,state: 'TX'},
					  {name: 'Burlington' ,state: 'VT'},
					  {name: 'Madison' ,state: 'AL'},
					  {name: 'Hallandale Beach' ,state: 'FL'},
					  {name: 'New Berlin' ,state: 'WI'},
					  {name: 'Sumter' ,state: 'SC'},
					  {name: 'Campbell' ,state: 'CA'},
					  {name: 'Culver City' ,state: 'CA'},
					  {name: 'Hurst' ,state: 'TX'},
					  {name: 'Dublin' ,state: 'OH'},
					  {name: 'Prescott Valley' ,state: 'AZ'},
					  {name: 'Huntsville' ,state: 'TX'},
					  {name: 'Urbandale' ,state: 'IA'},
					  {name: 'Calexico' ,state: 'CA'},
					  {name: 'Temple City' ,state: 'CA'},
					  {name: 'Brea' ,state: 'CA'},
					  {name: 'Meridian' ,state: 'MS'},
					  {name: 'Rock Island' ,state: 'IL'},
					  {name: 'Morgan Hill' ,state: 'CA'},
					  {name: 'Sherman' ,state: 'TX'},
					  {name: 'Cedar Falls' ,state: 'IA'},
					  {name: 'Romeoville' ,state: 'IL'},
					  {name: 'North Miami Beach' ,state: 'FL'},
					  {name: 'Ormond Beach' ,state: 'FL'},
					  {name: 'Apopka' ,state: 'FL'},
					  {name: 'Marlborough' ,state: 'MA'},
					  {name: 'Goose Creek' ,state: 'SC'},
					  {name: 'Florence' ,state: 'AL'},
					  {name: 'Smyrna' ,state: 'TN'},
					  {name: 'Wylie' ,state: 'TX'},
					  {name: 'San Jacinto' ,state: 'CA'},
					  {name: 'Lima' ,state: 'OH'},
					  {name: 'Carpentersville',state: 'IL'},
					  {name: 'Pacifica' ,state: 'CA'},
					  {name: 'Monrovia' ,state: 'CA'},
					  {name: 'Goldsboro' ,state: 'NC'},
					  {name: 'Stanton' ,state: 'CA'},
					  {name: 'Wausau' ,state: 'WI'},
					  {name: 'Cape Girardeau' ,state: 'MO'},
					  {name: 'Everett' ,state: 'MA'},
					  {name: 'New Albany' ,state: 'IN'},
					  {name: 'Germantown' ,state: 'TN'},
					  {name: 'Huber Heights' ,state: 'OH'},
					  {name: 'Streamwood', state: 'IL'},
					  {name: 'Findlay' ,state: 'OH'},
					  {name: 'Portage' ,state: 'IN'},
					  {name: 'Lancaster' ,state: 'OH'},
					  {name: 'Park Ridge' ,state: 'IL'},
					  {name: 'Lake Oswego' ,state: 'OR'},
					  {name: 'Addison' ,state: 'IL'},
					  {name: 'Woburn' ,state: 'MA'},
					  {name: 'Gadsden' ,state: 'AL'},
					  {name: 'Calumet City' ,state: 'IL'},
					  {name: 'Hanover Park',state: 'IL'},
					  {name: 'Kearny' ,state: 'NJ'},
					  {name: 'Richmond' ,state: 'IN'},
					  {name: 'Del Rio' ,state: 'TX'},
					  {name: 'Bell' ,state: 'CA'},
					  {name: 'Panama City' ,state: 'FL'},
					  {name: 'Texarkana' ,state: 'TX'},
					  {name: 'Manhattan Beach' ,state: 'CA'},
					  {name: 'Chester' ,state: 'PA'},
					  {name: 'Longview' ,state: 'WA'},
					  {name: 'Montclair' ,state: 'CA'},
					  {name: 'Annapolis' ,state: 'MD'},
					  {name: 'Plainfield',state: 'IL'},
					  {name: 'Riviera Beach' ,state: 'FL'},
					  {name: 'Norwich' ,state: 'CT'},
					  {name: 'Moorpark' ,state: 'CA'},
					  {name: 'Puyallup' ,state: 'WA'},
					  {name: 'University City' ,state: 'MO'},
					  {name: 'Fort Lee',state: 'NJ'},
					  {name: 'Mankato' ,state: 'MN'},
					  {name: 'Tupelo' ,state: 'MS'},
					  {name: 'Westerville' ,state: 'OH'},
					  {name: 'Brentwood' ,state: 'TN'},
					  {name: 'Beloit' ,state: 'WI'},
					  {name: 'Duncanville' ,state: 'TX'},
					  {name: 'Dover' ,state: 'DE'},
					  {name: 'Maplewood' ,state: 'MN'},
					  {name: 'Greenfield' ,state: 'WI'},
					  {name: 'Wheeling',state: 'IL'},
					  {name: 'Rome' ,state: 'GA'},
					  {name: 'Moorhead' ,state: 'MN'},
					  {name: 'Valley Stream',state: 'NY'},
					  {name: 'Bremerton' ,state: 'WA'},
					  {name: 'West Hollywood' ,state: 'CA'},
					  {name: 'Dunedin' ,state: 'FL'},
					  {name: 'Bartlesville' ,state: 'OK'},
					  {name: 'Keizer' ,state: 'OR'},
					  {name: 'Marion' ,state: 'OH'},
					  {name: 'Greenville' ,state: 'MS'},
					  {name: 'Lancaster' ,state: 'TX'},
					  {name: 'Alamogordo' ,state: 'NM'},
					  {name: 'Dana Point' ,state: 'CA'},
					  {name: 'Long Beach' ,state: 'NY'},
					  {name: 'Roy' ,state: 'UT'},
					  {name: 'Gainesville' ,state: 'GA'},
					  {name: 'Bentonville' ,state: 'AR'},
					  {name: 'Lake Worth' ,state: 'FL'},
					  {name: 'Franklin' ,state: 'WI'},
					  {name: 'Claremont' ,state: 'CA'},
					  {name: 'Minot' ,state: 'ND'},
					  {name: 'Cottonwood Heights' ,state: 'UT'},
					  {name: 'Lincoln Park' ,state: 'MI'},
					  {name: 'Torrington' ,state: 'CT'},
					  {name: 'Rockwall' ,state: 'TX'},
					  {name: 'Manassas' ,state: 'VA'}
=end

=begin
# for testing purposes only
cities = City.all
=end


neighborhood_hash = Hash.new

cities.each do |city|
    @name = city.name
    #replace any whitespace in the city name with a uri friendly %20
    @name = @name.split(' ').join('%20') if @name.split(' ').length > 1
    puts @name
    @id = city.id
    @state= city.state
    url = "https://api.foursquare.com/v2/venues/explore?near=#{@name},%20#{@state}&client_id=#{ENV['foursquare_id']}&client_secret=#{ENV['foursquare_secret']}&v=20150309&limit=50"
    #give me a list of interesting places according to foursquare related to the metro area    
	response = HTTParty.get(url)
	#for each explore response returned by 4 square, convert to lat/long
	if response["meta"]["code"]==400
		puts "error, Type: #{response['meta']['errorType']}, Detail: #{response['meta']['errorDetail']}"
		puts "url: #{url}"
	else
		response["response"]["groups"].first["items"].each do |venue_info|
			@ven_name = venue_info['venue']['name']
			@lat = venue_info['venue']['location']['lat']
			@lng = venue_info['venue']['location']['lng']
	        #build a uri for the neighborhood api I found
			neighborhood_url = "http://neighborhoodapi.com:80/v1/neighborhoods.json?lat=#{@lat}&lng=#{@lng}"
			neighborhood_response = HTTParty.get(neighborhood_url)
	        #not sure why it randomly doesn't respond sometimes, but it's only 1 in 3 or 4
	        if neighborhood_response.first.nil?
	        	puts "no response from neighborhoods for #{@ven_name}"
	        	puts "url: #{neighborhood_url}"
	        else
	        	#grab our neighborhood name returned from the api
	        	hood_name = neighborhood_response.first['neighborhood']['name']
	        	#if our neighborhood name doesn't exist, store it's lat/long as a 2 item list in it's value
	        	if neighborhood_hash[hood_name].nil?
	        		neighborhood_hash[hood_name] = [@lat,@lng]
	        	end
	        end
		end
	    neighborhood_hash.each do |name,lat_lon|
	    	Neighborhood.create([{name: name,
	    	                      city_id: @id,
	    		                  latitude: lat_lon[0], 
	    		                  longitude:lat_lon[1]}])
	    	neighborhood_hash.delete(name)
	    end
	end

end

r = City.all()
r.each do |city|
	len = Neighborhood.where(city_id: city.id).length
	if len <= 5
		puts "#{city.name}, #{city.state} needs some help, they've only got #{len} neighborhoods! "
	else
		puts "#{city.name}, #{city.state} has #{len} neighborhoods on record "
	end
end

